name: Java CI with Maven

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - checkout main branch from GitHub
      uses: actions/checkout@v2
      
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Step 3 - GitHub Actions Build Maven Project
      run: mvn -B package --file pom.xml
      
    - name: Step 4 - List the current directory
      run: ls -a
   
    - name: Step 5 - what is in the target folder?
      run: |
        cd target
        ls -a
      
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
